apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twopc
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: twopc
    spec:
      containers:
      - name: twopc
        image: sebastianharko/2pc:2.8
        imagePullPolicy: Always
        env:
        - name: HTTP_TIMEOUT
          value: "1200"
        - name: ACCOUNT_TIMEOUT
          value: "600"
        - name: VOTING_TIMEOUT
          value: "600"
        - name: COMMIT_TIMEOUT
          value: "300"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP 
        ports:
        - containerPort: 8080
        - containerPort: 19999
        - containerPort: 2551
        resources:
          requests:
            cpu: 3
            memory: 6Gi 
          limits:
            cpu: 3
            memory: 6Gi
---
kind: Service
apiVersion: v1
metadata:
  name: twopc
spec:
  selector:
    app: twopc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 0.0.0.0/0
