apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: accounts
spec:
  replicas: 1
  template:
    metadata:
    spec:
      containers:
      - name: twopc
        image: sebastianharko/2pc:6.0
        imagePullPolicy: Always
        env:
        - name: ROLE0
          value: "ACCOUNT"
        - name: CASS
          value: "cassandra-0.cassandra.default.svc.cluster.local"
        - name: NUM_SHARDS_ACCOUNTS
          value: "50"
        - name: ACCOUNT_TIMEOUT
          value: "1000"
        - name: PASSIVATE_ACCOUNT
          value: "120"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP 
        ports:
        - containerPort: 8080
        - containerPort: 19999
        - containerPort: 2551
        resources:
          requests:
            cpu: 8
            memory: 32Gi
          limits:
            cpu: 8
            memory: 32Gi
--
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coordinators
spec:
  replicas: 1
  template:
    metadata:
    spec:
      containers:
      - name: twopc
        image: sebastianharko/2pc:6.0
        imagePullPolicy: Always
        env:
        - name: ROLE0
          value: "COORDINATOR"
        - name: CASS
          value: "cassandra-0.cassandra.default.svc.cluster.local"
        - name: NUM_SHARDS_COORD
          value: "50"
        - name: PASSIVATE_COORD
          value: "120"
        - name: VOTING_TIMEOUT
          value: "1200"
        - name: COMMIT_TIMEOUT
          value: "500"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8080
        - containerPort: 19999
        - containerPort: 2551
        resources:
          requests:
            cpu: 8
            memory: 32Gi
          limits:
            cpu: 8
            memory: 32Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: twopc
    spec:
      containers:
      - name: twopc
        image: sebastianharko/2pc:6.0
        imagePullPolicy: Always
        env:
        - name: ROLE0
          value: "HTTP"
        - name: CASS
          value: "cassandra-0.cassandra.default.svc.cluster.local"
        - name: QUERY_HTTP_TIMEOUT
          value: "400"
        - name: HTTP_TIMEOUT
          value: "300"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8080
        - containerPort: 19999
        - containerPort: 2551
        resources:
          requests:
            cpu: 2
            memory: 2Gi
          limits:
            cpu: 2
            memory: 2Gi


