apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twopc
spec:
  replicas: 8 
  template:
    metadata:
      labels:
        app: twopc
    spec:
      containers:
      - name: twopc
        image: sebastianharko/2pc:3.1
        imagePullPolicy: Always
        env:
        - name: QUERY_HTTP_TIMEOUT
          value: "800"
        - name: HTTP_TIMEOUT
          value: "1500"
        - name: ACCOUNT_TIMEOUT
          value: "1000"
        - name: VOTING_TIMEOUT
          value: "1000"
        - name: COMMIT_TIMEOUT
          value: "1000"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP 
        ports:
        - containerPort: 8080
        - containerPort: 19999
        - containerPort: 2551
        resources:
          requests:
            cpu: 2
            memory: 6Gi 
          limits:
            cpu: 2
            memory: 6Gi

