apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twopc
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: twopc
    spec:
      containers:
      - name: twopc
        image: sebastianharko/2pc:3.0
        imagePullPolicy: Always
        env:
        - name: HTTP_TIMEOUT
          value: "1200"
        - name: ACCOUNT_TIMEOUT
          value: "600"
        - name: VOTING_TIMEOUT
          value: "600"
        - name: COMMIT_TIMEOUT
          value: "300"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP 
        ports:
        - containerPort: 8080
        - containerPort: 19999
        - containerPort: 2551
        resources:
          requests:
            cpu: 2
            memory: 6Gi 
          limits:
            cpu: 2
            memory: 6Gi

