apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twopc
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: twopc
    spec:
      containers:
      - name: twopc
        image: sebastianharko/2pc:4.4
        imagePullPolicy: Always
        env:
        - name: NUM_SHARDS
          value: "28"
        - name: QUERY_HTTP_TIMEOUT
          value: "550"
        - name: HTTP_TIMEOUT
          value: "1400"
        - name: ACCOUNT_TIMEOUT
          value: "2500"
        - name: VOTING_TIMEOUT
          value: "2000"
        - name: COMMIT_TIMEOUT
          value: "1000"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP 
        ports:
        - containerPort: 8080
        - containerPort: 19999
        - containerPort: 2551
        resources:
          requests:
            cpu: 5 
            memory: 15Gi 
          limits:
            cpu: 5
            memory: 15Gi

