apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        args:
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://etcd:2379
        image: quay.io/coreos/etcd:v2.3.7
        ports:
        - containerPort: 2379
        resources:
          requests:
            cpu: 0.5
            memory: 2Gi
          limits:
            cpu: 0.5
            memory: 2Gi
---
kind: Service
apiVersion: v1
metadata:
  name: etcd
spec:
  selector:
    app: etcd
  ports:
    - protocol: TCP
      port: 2379
      targetPort: 2379
