---
kind: Service
apiVersion: v1
metadata:
  name: http-service
spec:
  selector:
    app: http
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 0.0.0.0/0
