apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ggs 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ggs 
    spec:
      containers:
      - name: grafana-grafana-statsd 
        image: marial/grafana-graphite-statsd
        ports:
        - containerPort: 80
          name: grafaa
        - containerPort: 2003
          name: carbon
        - containerPort: 8125
          name: udp
        - containerPort: 8126
          name: statsd
        resources:
          requests:
            cpu: 2
            memory: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: grafana 
spec:
  type: LoadBalancer
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: ggs
  loadBalancerSourceRanges:
    - 0.0.0.0/0
---
apiVersion: v1
kind: Service
metadata:
  name: sd 
spec:
  type: LoadBalancer
  ports: 
    - protocol: UDP
      port: 8125
      targetPort: 8125
  selector:
    app: ggs
